In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [5]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [6]:
indep

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVC

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel':['linear', 'poly', 'rbf','sigmoid'],
             'gamma':['auto','scale'],
             'C':[10,100,1000,2000,3000],
             'decision_function_shape':['ovo', 'ovr']} 

grid = GridSearchCV(SVC(probability=True), param_grid, refit = True, verbose = 3,cv=5,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 80 candidates, totalling 400 fits


GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'decision_function_shape': ['ovo', 'ovr'],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [13]:
print(cm)

[[51  0]
 [ 1 81]]


In [14]:
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9924946382275899


In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.006659      0.004559         0.003395        0.001938      10   
1        0.008501      0.003902         0.004658        0.004154      10   
2        0.006283      0.003884         0.004827        0.004998      10   
3        0.003811      0.002102         0.004407        0.003314      10   
4        0.004976      0.001857         0.003015        0.000908      10   
..            ...           ...              ...             ...     ...   
75       0.004642      0.001888         0.002389        0.001510    3000   
76       0.002425      0.003214         0.002298        0.003002    3000   
77       0.008136      0.002419         0.003087        0.002711    3000   
78       0.003311      0.002188         0.003560        0.003152    3000   
79       0.001114      0.001440         0.003603        0.004458    3000   

   param_decision_function_shape param_gamma param_kernel  \
0                            ovo        auto       linear   
1                            ovo        auto         poly   
2                            ovo        auto          rbf   
3                            ovo        auto      sigmoid   
4                            ovo       scale       linear   
..                           ...         ...          ...   
75                           ovr        auto      sigmoid   
76                           ovr       scale       linear   
77                           ovr       scale         poly   
78                           ovr       scale          rbf   
79                           ovr       scale      sigmoid   

                                               params  split0_test_score  \
0   {'C': 10, 'decision_function_shape': 'ovo', 'g...           0.981569   
1   {'C': 10, 'decision_function_shape': 'ovo', 'g...           1.000000   
2   {'C': 10, 'decision_function_shape': 'ovo', 'g...           0.963284   
3   {'C': 10, 'decision_function_shape': 'ovo', 'g...           0.981569   
4   {'C': 10, 'decision_function_shape': 'ovo', 'g...           0.981569   
..                                                ...                ...   
75  {'C': 3000, 'decision_function_shape': 'ovr', ...           0.981569   
76  {'C': 3000, 'decision_function_shape': 'ovr', ...           0.981569   
77  {'C': 3000, 'decision_function_shape': 'ovr', ...           0.963284   
78  {'C': 3000, 'decision_function_shape': 'ovr', ...           0.963284   
79  {'C': 3000, 'decision_function_shape': 'ovr', ...           0.981569   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.962636           0.962573           0.981031   
1            0.981014           1.000000           1.000000   
2            0.981014           1.000000           1.000000   
3            1.000000           1.000000           0.981031   
4            0.962636           0.962573           0.981031   
..                ...                ...                ...   
75           0.943699           0.962573           0.981031   
76           0.962636           0.962573           0.981031   
77           0.981014           0.981217           1.000000   
78           0.981014           1.000000           0.981031   
79           0.943699           0.962573           0.981031   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.981217         0.973805        0.009147               45  
1            0.981217         0.992446        0.009252                5  
2            1.000000         0.988859        0.014751                7  
3            1.000000         0.992520        0.009163                1  
4            0.981217         0.973805        0.009147               45  
..                ...              ...             ...              ...  
75           0.981217         0.970018        0.015021               69  
76           0.981217         0.973805        0.009147               45  
77           0.981217 

In [20]:
import pickle
filename="finilized_model_SVC.sav"

In [21]:
pickle.dump(grid,open(filename,'wb'))

In [22]:
preinput_data = [[22, 2.0, 3.0, 2.0, 31.1, 31.0, 21.0, 21.4, 21.0, 22.1, 12, 42, 23, 23, 23, 12, 21, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1]]

In [23]:
preinput = sc.transform(preinput_data)

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [24]:
preinput

array([[ -1.84081659,  -5.73912749,   1.75234707,   1.65360436,
         -1.5533662 ,  -0.5523541 ,   2.99737758, -11.03112894,
          7.38062207,   3.56013652,  -3.32344039,  -3.44743899,
         22.44974661,  57.50344284,  54.16462312,  31.55690113,
        154.49227435,   0.38924947,   0.51055216,   2.91547595,
          4.24264069,  -0.73926425,  -0.73926425,  -0.29277002,
          0.51639778,   1.91485422,   2.24620893]])

In [25]:
loaded_model=pickle.load(open("finilized_model_SVC.sav",'rb'))
result=loaded_model.predict(preinput)

In [26]:
result

array([1])